gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/overcommit'
      - 'libexec/**/*'
      - 'template-dir/hooks/**/*'

  HardTabs:
    enabled: true

  RuboCop:
    enabled: true
    include:
      - '**/*.gemspec'
      - '**/*.rb'
      - '**/Gemfile'
      - template-dir/hooks/overcommit-hook

  TravisLint:
    enabled: true
    flags: ['lint', '--skip-version-check']

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
