AmbiguousRegexpLiteral:
  Enabled: false

AccessModifierIndentation:
  EnforcedStyle: outdent

AssignmentInCondition:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
ClassAndModuleChildren:
  Enabled: false

CollectionMethods:
  Enabled: false

Documentation:
  Exclude:
    - 'spec/overcommit/**/*'

# Ruby 1.8.7 only supports trailing dots in method chains, but Rubocop still
# reports it as an error for method calls chained onto do...end blocks. That's
# too much noise, so remove it.
DotPosition:
  Enabled: false

# Ruby 1.8.7 doesn't have `each_with_object` defined.
EachWithObject:
  Enabled: false

Encoding:
  EnforcedStyle: when_needed

FileName:
  Exclude:
    - 'template-dir/hooks/*'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

FormatString:
  Enabled: false

# There are a number of situations where this makes code less readable or
# disrupts the visual flow of code.
GuardClause:
  Enabled: false

# Ruby 1.8.7 only supports hash rockets.
HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

# We want to allow multi-line lambdas using the `->` syntax which Rubocop
# doesn't allow. We're also not too worried about people using `lambda` for
# single-line lambdas either.
Lambda:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 20

Next:
  Enabled: false

# Prefer curly braces except for %i/%w/%W, since those return arrays.
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
PredicateName:
  Enabled: false

SignalException:
  Enabled: false

# Forcing a particular name (e.g. |a, e|) for inject methods prevents you from
# choosing intention-revealing names.
SingleLineBlockParams:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Exclude:
    - '*.gemspec'

SpecialGlobalVars:
  Enabled: false

TrailingComma:
  Enabled: false

Void:
  Enabled: false
