AccessModifierIndentation:
  EnforcedStyle: outdent

CollectionMethods:
  Enabled: false

# Ruby 1.8.7 only supports trailing dots in method chains, but Rubocop still
# reports it as an error for method calls chained onto do...end blocks. That's
# too much noise, so remove it.
DotPosition:
  Enabled: false

# Ruby 1.8.7 only supports hash rockets.
HashSyntax:
  EnforcedStyle: hash_rockets

LineLength:
  Max: 100

MethodLength:
  Max: 20

TrailingComma:
  Enabled: false

Void:
  Enabled: false
