rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-19mode
before_script:
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis CI"
script: bundle exec rspec
