language: ruby

sudo: false

cache: bundler

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-19mode

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
